### ISSUE TITLE
ascii unicode error?

### ISSUE THREAD

**Issue by jlstanus** [martinGithub/beamer2pptx#2]
Hello, don't know what could be...

> WARNING: unrecognized command/environment: PassOptionsToPackage
> .......
> WARNING: unrecognized command/environment: @firstoftwo
> WARNING: unrecognized command/environment: pdfobj
> WARNING: unrecognized command/environment: pdfrefobj
> WARNING: unrecognized command/environment: pdflastobj
> .... )
>  ( /usr/local/lib/python2.7/dist-packages/plasTeX/Packages/hyperref.pyc )..
> WARNING: unrecognized command/environment: graphicspath
> WARNING: unrecognized command/environment: hypersetup
> ..
> ERROR: Error while reading argument "self" of title in <string> on line 26
>    ('ascii' codec can't decode byte 0xc3 in position 0: ordinal not in
>    range(128))
> ERROR: Error while expanding "title" in <string> on line 26 ('ascii' codec
>    can't decode byte 0xc3 in position 0: ordinal not in range(128))
> ERROR: An error occurred while building the document object in <string> on
>    line 26 ('ascii' codec can't decode byte 0xc3 in position 0: ordinal not in
>    range(128))
> could not parse the latex fil eusing plasTex
> Traceback (most recent call last):
>   File "beamer2pptx.py", line 75, in <module>
>     document = tex.parse()
>   File "/usr/local/lib/python2.7/dist-packages/plasTeX/TeX.py", line 412, in parse
>     for item in tokens:
>   File "/usr/local/lib/python2.7/dist-packages/plasTeX/TeX.py", line 46, in next
>     return self._next()
>   File "/usr/local/lib/python2.7/dist-packages/plasTeX/TeX.py", line 321, in __iter__
>     tokens = obj.invoke(self)
>   File "/usr/local/lib/python2.7/dist-packages/plasTeX/Base/LaTeX/Packages.py", line 160, in invoke
>     Command.invoke(self, tex)
>   File "/usr/local/lib/python2.7/dist-packages/plasTeX/**init**.py", line 366, in invoke
>     self.parse(tex)
>   File "/usr/local/lib/python2.7/dist-packages/plasTeX/**init**.py", line 476, in parse
>     **arg.options)
>   File "/usr/local/lib/python2.7/dist-packages/plasTeX/TeX.py", line 722, in readArgumentAndSource
>     toks, source = self.readToken(expanded, parentNode=parentNode)
>   File "/usr/local/lib/python2.7/dist-packages/plasTeX/TeX.py", line 784, in readToken
>     for t in tokens:
>   File "/usr/local/lib/python2.7/dist-packages/plasTeX/TeX.py", line 244, in itertokens
>     t = inputs[-1][-1].next()
>   File "/usr/local/lib/python2.7/dist-packages/plasTeX/Tokenizer.py", line 368, in **iter**
>     token = next()
>   File "/usr/local/lib/python2.7/dist-packages/plasTeX/Tokenizer.py", line 272, in iterchars
>     code = whichCode(token)
>   File "/usr/local/lib/python2.7/dist-packages/plasTeX/Context.py", line 716, in whichCode
>     if char in c[Token.CC_LETTER]:
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)

**Comment by martinGithub** [comment]
Looks like there is something wrong with your Tex file and plastek can't parse it. But I'm actually not using plastek yet in the rest of the code, so you can try to simply comment the lines from the "try" to the "raise"

**Comment by martinGithub** [comment]
I made the change
